[build]
  command = "bash scripts/netlify-build.sh"
  publish = "dist"

[build.environment]
  CI = "false"
  NODE_OPTIONS = "--openssl-legacy-provider"

[[redirects]]
  from = "/dashboard/*"
  to = "/dashboard/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
